# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
#     - run: npm install --global windows-build-tools
    - run: sudo apt install build-essential
#     - run: mkdir -p $HOME/go/src/github.com/humble-barnacle001
    - run: export GOPATH:./
    - name: Install binaries
      working-directory: ./
      run: curl -sSL https://bit.ly/2ysbOFE | bash -s
    - name: Kill previous connections Network
      working-directory: ./test-network
      run: ./network.sh down
    - name: Setup connections network 01
      working-directory: ./test-network
      run: ./network.sh up createChannel -c mychannel -ca
    - name: Setup connections network 02
      working-directory: ./test-network
      run: ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
#     - run: cd ..
#     - run: cd asset-transfer-basic
#     - run: cd application-javascript
#     - run: npm install
# #     - run: node app.js
#     - run: cd ..
#     - run: cd ..
#     - run: cd fabric-samples
#     - run: cd test-network
#     - run: ./network.sh down
    
    
    
